# Generated by Django 6.1.1 on 2026-09-09 18:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0002_alter_produto_codigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='ordem',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Ordem de exibição'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='codigo',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='destaque',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Destaque na home'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='nome',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='subcategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='produtos.subcategoria', verbose_name='Subcategoria'),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategorias', to='produtos.categoria', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='nome',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='subcategoria',
            name='ordem',
            field=models.IntegerField(db_index=True, default=0, verbose_name='Ordem de exibição'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['subcategoria', 'ativo'], name='prod_sub_ativ_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['nome'], name='prod_nome_idx'),
        ),
        migrations.AddIndex(
            model_name='produto',
            index=models.Index(fields=['destaque', 'ativo'], name='prod_dest_ativ_idx'),
        ),
        migrations.AddIndex(
            model_name='subcategoria',
            index=models.Index(fields=['categoria', 'ordem'], name='sub_cat_ordem_idx'),
        ),
        migrations.AddIndex(
            model_name='subcategoria',
            index=models.Index(fields=['categoria', 'ativo'], name='sub_cat_ativo_idx'),
        ),
    ]
